# Generated by Django 5.0.6 on 2024-07-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255, null=True)),
                ('twitter', models.CharField(max_length=255, null=True)),
                ('facebook', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
