# Generated by Django 5.0.6 on 2024-07-07 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_alter_team_facebook_alter_team_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Reservation Day',
                'verbose_name_plural': 'Reservation Days',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=12)),
                ('text', models.TextField()),
                ('time', models.TimeField(verbose_name='Time')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='clinic.reservationday', verbose_name='Day')),
            ],
            options={
                'verbose_name': 'Reservation',
                'verbose_name_plural': 'Reservations',
                'ordering': ('time',),
            },
        ),
    ]
