# Generated by Django 5.0.6 on 2024-07-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_reservation_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='doctor',
            field=models.CharField(choices=[('D1', 'Doctor1'), ('D2', 'Doctor2'), ('D3', 'Doctor3')], default='D1', max_length=255),
        ),
    ]
