# Generated by Django 5.0.6 on 2024-07-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_reservationday_alter_reservation_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='FreeReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
