# Generated by Django 5.0.6 on 2024-07-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_freereservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='freereservation',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
