# Generated by Django 5.0.6 on 2024-07-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_freereservation_is_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='day',
            field=models.DateField(verbose_name='Day'),
        ),
        migrations.DeleteModel(
            name='ReservationDay',
        ),
    ]
