# Generated by Django 5.0.6 on 2024-07-10 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_reservationday_alter_freereservation_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freereservation',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinic.reservationday', verbose_name='Day'),
        ),
    ]
